src/KAssessment/KAssessment/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Models.Entities;

namespace KAssessment.Controllers
{
    public class GroupController : Controller
    {
        private readonly IOrganizationRepository organizationRepository;
        public GroupController(IOrganizationRepository organizationRepository)
        {
            this.organizationRepository = organizationRepository;
        }
        [HttpGet]
        public IActionResult Index(int specialtyId = 0)
        {
            return View(organizationRepository.GetGroups(specialtyId));
        }
        [HttpGet]
        public IActionResult Modify([FromRoute]int id = 0)
        {
            ModifyGroupModel model = new ModifyGroupModel();
            model.Specialties = organizationRepository.GetSpecialties();

            if (id == 0)
            {
                model.Group = new Group();
            }
            else
            {
                model.Group = organizationRepository.GetGroup(id);
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult Modify(Group group)
        {
            organizationRepository.EditGroup(group);
            return Redirect("Index");
        }
        [HttpDelete]
        public IActionResult DeactivateGroup(int groupId)
        {
            organizationRepository.DeleteGroup(groupId);
            return Redirect("Index");
        }  
    }
}

src/KAssessment/KAssessment/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Models.Entities;

namespace KAssessment.Controllers
{
    public class OrganizationController : Controller
    {
        private readonly IOrganizationRepository organizationRepository;
        private readonly ITeacherRepository teacherRepository;
        public OrganizationController(ITeacherRepository teacherRepository, IOrganizationRepository organizationRepository)
        {
            this.teacherRepository = teacherRepository;
            this.organizationRepository = organizationRepository;
        }
        [HttpGet]
        public IActionResult Teacher([FromQuery]int teacherId)
        {
            var teacher = teacherRepository.GetTeacher(teacherId);
            return View(teacher);
        }
        [HttpGet]
        public IActionResult Teachers()
        {
            var teachers = teacherRepository.GetTeachers();
            return View(teachers);
        }
        [HttpGet]
        [ActionName("ModifyTeacher")]
        public IActionResult ModifyTeacher([FromRoute]int id = 0)
        {
            var teacher = id == 0 ? new TeacherInfoModel() : teacherRepository.GetTeacher(id);
            return View(teacher);
        }
        [HttpPost]
        public async Task<IActionResult> ModifyTeacher(TeacherInfoModel teacherInfo)
        {
            await teacherRepository.ModifyTeacher(teacherInfo);
            return RedirectToAction("Teachers");
        }
        public IActionResult DeactivateTeacher([FromRoute]int id = 0)
        {
            teacherRepository.DeactivateTeacher(id);
            return RedirectToAction("Teachers");
        }
        public IActionResult ActivateTeacher([FromRoute]int id = 0)
        {
            teacherRepository.ActivateTeacher(id);
            return RedirectToAction("Teachers");
        }
        [HttpGet]
        public IActionResult Specialties()
        {
            return View(organizationRepository.GetSpecialties());
        }
        [HttpGet]
        public async Task<IActionResult> ModifySpecialty([FromRoute]int id = 0)
        {
            return View(await organizationRepository.GetSpecialty(id));
        }
        [HttpPost]
        public async Task<IActionResult> ModifySpecialty(Specialty specialty)
        {
            await organizationRepository.EditSpecialty(specialty);
            return RedirectToAction("Specialties");
        }
        [HttpDelete]
        public IActionResult DeleteSpecialty(int specialtyId)
        {
            organizationRepository.DeleteSpecialty(specialtyId);
            return RedirectToAction("Specialties");
        }
    }
}

src/KAssessment/KAssessment/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer;
using Microsoft.AspNetCore.Mvc;

namespace KAssessment.Controllers
{
    public class StudentController : Controller
    {
        private readonly Repository repository;
        public StudentController(Repository repository)
        {
            this.repository = repository;
        }
        [HttpGet]
        public IActionResult Group([FromRoute]int id)
        {
            return View(repository.Organization.GetGroupStudents(id));
        }
        [HttpGet]
        public IActionResult OpenedTests()
        {
            var student = repository.Students.GetStudentByUsername(User.Identity.Name);
            return View(repository.Tests.GetActiveTestForStudent(student.StudentId));
        }
    }
}

src/KAssessment/KAssessment/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Models.Entities;

namespace KAssessment.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ISubjectRepository subjectRepository;
        public SubjectController(ISubjectRepository subjectRepository)
        {
            this.subjectRepository = subjectRepository;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View(subjectRepository.GetSubjects());
        }
        [HttpPost]
        public IActionResult Modify(Subject subject)
        {
            subjectRepository.ModifySubject(subject);
            return Redirect("Index");
        }
    }
}

src/KAssessment/KAssessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KAssessment Система тестування знань</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand">KAssessment</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="basicExampleNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Головна</a></li>
                @if (@User.IsInRole(Models.Enums.Roles.Admin.ToString()))
                {
                    <li class="nav-item"><a class="nav-link" asp-controller="Group" asp-action="Index">Групи</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Organization" asp-action="Teachers">Викладачі</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Organization" asp-action="Specialties">Спеціальності</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Subject" asp-action="Index">Дисципліни</a></li>
                }
                @if (@User.IsInRole(Models.Enums.Roles.Teacher.ToString()))
                {
                    <li class="nav-item"><a class="nav-link" asp-controller="Teacher" asp-action="Courses">Мої курси</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Teacher" asp-action="Tests">Мої Тести</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Teacher" asp-action="ActiveTests">Запущені тести</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Teacher" asp-action="Results">Результати</a></li>
                }
                @if (@User.IsInRole(Models.Enums.Roles.Student.ToString()))
                {
                    <li class="nav-item"><a class="nav-link" asp-controller="Student" asp-action="OpenedTests">Відкриті тести</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Student" asp-action="Subjects">Предмети</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Student" asp-action="Results">Результати</a></li>
                }

            </ul>
            @if (User.Identity.IsAuthenticated)
            {
                <ul class="navbar-nav navbar-right">
                    <li class="nav-item">
                        <a class="nav-link" style="color:white">@User.Identity.Name</a>
                    </li>
                    <li>
                        <form method="post" asp-controller="Account" asp-action="LogOff">
                            <button class="btn btn-info navbar-btn" type="submit">Вийти</button>
                        </form>
                    </li>
                </ul>
            }
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer className="page-footer font-small bg-primary">
            <div className="footer-copyright text-center py-3">
                <div className="container">
                    © @DateTime.Now.Year KAssessment - Розроблено для ВТК
                </div>
            </div>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquert-unobtrusive/jquery-unobtrusive-ajax.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>