src/KAssessment/KAssessment/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Models.Entities;

namespace KAssessment.Controllers
{
    public class CourseController : Controller
    {
        private readonly ITeacherRepository teacherRepository;
        private readonly IOrganizationRepository organizationRepository;
        private readonly ISubjectRepository subjectRepository;
        public CourseController(ITeacherRepository teacherRepository, IOrganizationRepository organizationRepository, ISubjectRepository subjectRepository)
        {
            this.teacherRepository = teacherRepository;
            this.organizationRepository = organizationRepository;
            this.subjectRepository = subjectRepository;
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Groups = organizationRepository.GetAvailableGroups();
            ViewBag.Subjects = subjectRepository.GetSubjects();
            return View(new CreateCourseDTO());
        }
        [HttpPost]
        public IActionResult Create(CreateCourseDTO createCourse)
        {
            var teacherUserName = User.Identity.Name;
            createCourse.TeacherId = teacherRepository.GetTeacherByUserName(teacherUserName).Id;
            teacherRepository.CreateCourse(createCourse);
            return RedirectToAction("Courses","Teacher");
        }
    }
}

src/KAssessment/KAssessment/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer;
using Microsoft.AspNetCore.Mvc;

namespace KAssessment.Controllers
{
    public class SessionController : Controller
    {
        private readonly Repository _repository;
        public SessionController(Repository repository)
        {
            _repository = repository;
        }
        public IActionResult Start([FromRoute]int id)
        {
            //_repository.Tests.StartTest(id);
            return View();
        }
        public IActionResult Result([FromRoute]int id)
        {
            return View();
        }
    }
}

src/KAssessment/KAssessment/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer;
using DataAccessLayer.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.Entities;

namespace KAssessment.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class TeacherController : Controller
    {
        private Repository repository;
        public TeacherController(Repository repository)
        {
            this.repository = repository;
        }
        [HttpGet]
        public IActionResult Courses()
        {
            var teacherCourses = repository.Teachers.GetTeacherCourses(User.Identity.Name);
            return View(teacherCourses);
        }
        [HttpGet]
        public IActionResult Tests()
        {
            var teacherTests = repository.Teachers.GetTeacherTests(User.Identity.Name);
            return View(teacherTests);
        }
        [HttpGet]
        public IActionResult ModifyTest(int testId = 0, int subjectId = 0)
        {
            ViewBag.Subjects = repository.Subjects.GetSubjects();
            ViewBag.SelectedSubject = subjectId;
            var test = testId == 0 ? new Test() : repository.Tests.GetTest(testId);
            return View(test);
        }
        [HttpPost]
        public IActionResult ModifyTest(Test test)
        {
            test.TeacherId = repository.Teachers.GetTeacherByUserName(User.Identity.Name).Id;
            repository.Tests.ModifyTest(test);
            return RedirectToAction("Tests");
        }
        [HttpGet]
        public IActionResult TestQuestions([FromRoute]int id)
        {
            var testInfo = repository.Tests.GetTestWithQuestions(id);
            return View(testInfo);
        }
        [HttpPost]
        public IActionResult ModifyQuestion(Question question)
        {
            repository.Tests.ModifyTestQuestion(question);
            return RedirectToAction("TestQuestions", new { id = question.TestId });
        }
        [HttpDelete]
        public IActionResult DeleteTest(int testId)
        {
            repository.Tests.DeleteTest(testId);
            return RedirectToAction("Tests");
        }
        [HttpPost]
        public IActionResult ModifyAnswer(Answer answer)
        {
            var result = repository.Tests.ModifyQuestionAnswer(answer);
            var question = repository.Tests.GetQuestion(result.QuestionId);
            return PartialView("_QuestionAnswers", question);
        }
        [HttpPost]
        public IActionResult DeleteAnswer(int id)
        {
            var answer = repository.Tests.GetAnswer(id);
            repository.Tests.DeleteAnswer(id);
            var question = repository.Tests.GetQuestion(answer.QuestionId);
            return PartialView("_QuestionAnswers", question);
        }
        [HttpGet]
        public IActionResult Course(int subjectId,int teacherId,int groupId)
        {
            var model = repository.Course.GetCourseInfo(subjectId:subjectId,teacherId:teacherId,groupId:groupId);
            ViewBag.AvailableTests = repository.Teachers.GetTeacherTests(User.Identity.Name,subjectId).FirstOrDefault()?.Tests;
            return View(model);
        }
        [HttpPost]
        public IActionResult Session(TestSession testSession)
        {
            repository.Tests.ModifySession(testSession);
            return PartialView("_TestSessions",
                repository.Tests.GetSessions(testSession.CourseId));
        }
    }
}

src/KAssessment/KAssessment/Views/Teacher/Course.cshtml
@model Models.Entities.Course
@{
    ViewData["Title"] = "Курс " + Model.Subject.Name;
}

<h2>Курс @Model.Subject.Name групи @Model.Group.Name</h2>

<div>
    <form class="addSessionForm"
          action="/teacher/Session"
          method="post"
          data-ajax-update="#sessions"
          data-ajax="true"
          data-ajax-method="post"
          data-ajax-complete="completed">

        <h4>Запустити тест</h4>
        <div>
            <div class="row form-group">
                <input type="hidden" value="@Model.Id" name="CourseId" />
                <div class="col-md-4">
                    <label>Виберіть тест:</label>
                </div>
                <div class="col-md-4">
                    <select name="TestId" class="form-control">
                        @foreach (var test in ViewBag.AvailableTests)
                        {
                            <option value="@test.Id">@test.Name</option>
                        }
                    </select>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-md-4">
                    <label>Виділено хвилин на тест:</label>
                </div>
                <div class="col-md-4">
                    <input type="number" class="form-control" name="TimeToLiveInMinutes" />
                </div>
            </div>
        </div>
        <div>
            <button type="submit" class="btn btn-success">Запустити</button>
        </div>
    </form>
</div>
<div style="margin-top:20px">
    <table class="table table-sm table-striped table-bordered">
        <thead>
            <tr>
                <th>Назва тесту</th>
                <th>Час початку</th>
                <th>Час закінчення</th>
                <th>Результати</th>
            </tr>
        </thead>
        <tbody id="sessions">
            @Html.Partial("_TestSessions", Model.TestSessions)
        </tbody>
    </table>
</div>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-success" style="color:white">
                <h5>KAssestment</h5>
                <button class="close" data-dismiss="modal" area-hidden="true">X</button>
            </div>
            <div class="modal-body"  >
                <h4 style="text-align:center">Тест запущенно</h4>
            </div>
        </div>
    </div>
</div>

<script>

    completed = function () {
        document.getElementsByName("TimeToLiveInMinutes")[0].value = "";
        $("#modDialog").modal('show')
        };
</script>

src/KAssessment/KAssessment/Views/Teacher/Courses.cshtml
@model IEnumerable<Models.Entities.Course>

@{
    ViewData["Title"] = "Мої курси";
}

<h2>Мої курси</h2>

<p>
    <a class="btn btn-info" href="/course/create">
        Створити курс
    </a>
</p>

<table class="table table-sm table-striped table-bordered">
    <tr>
        <th>Група</th>
        <th>Дисципліна</th>
        <th>Викладач</th>
        <th>Дата початку</th>
        <th>Тести</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr
            @if(new DateTime(item.Group.YearOfEnd,7,1)<DateTime.Now)
            {
                @:style="border:2px dashed red"
            }
            >
            <td>@item.Group.Name</td>
            <td>@item.Subject.Name</td>
            <td>@item.Teacher.FullName</td>
            <td>@item.CreatedDate.ToShortDateString()</td>
            <td><a href="/teacher/course?groupId=@item.Group.Id&teacherId=@item.Teacher.Id&subjectId=@item.Subject.Id">Тести</a></td>
        </tr>
    }
</table>

src/KAssessment/KAssessment/Views/Teacher/ModifyTest.cshtml
@model Models.Entities.Test
@{
    ViewData["Title"] = (Model.Id == 0 ? "Створити" : "Редагувати") + " тест";
}

<h2>@((Model.Id == 0 ? "Створити" : "Редагувати") + " тест")</h2>


<div class="panel panel-success">
    <div class="panel-heading text-center"><h4>Інформація про тест</h4></div>
    <div class="panel-body">
        <form class="p-a-1" asp-action="ModifyTest" method="post">
            <div asp-validation-summary="All"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SubjectId">Виберіть дисципліну:</label>
                <select asp-for="SubjectId" class="form-control selectpicker">
                    @foreach (var item in ViewBag.Subjects)
                    {
                        if (ViewBag.SelectedSubject != null && ViewBag.SelectedSubject != 0 && item.Id == ViewBag.SelectedSubject)
                        {
                            <option value="@item.Id" selected>@item.Name</option>
                        }
                        else
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Name">Назва тесту:</label>
                <input class="form-control" asp-for="Name" />
            </div>
            <div class="form-group">
                <label asp-for="Description">Опис тесту:</label>
                <input class="form-control" asp-for="Description" />
            </div>
            <div class="form-group">
                <label asp-for="NumberOfQuestions">Стандартна к-сть питань:</label>
                <input class="form-control" asp-for="NumberOfQuestions" type="number" />
            </div>

            <div class="text-center">
                <button class="btn btn-primary" type="submit">
                    @(Model.Id == 0 ? "Створити" : "Зберегти")
                </button>
                <a class="btn btn-danger" href="/teacher/tests">
                    Відмінити
                </a>
                @if (Model.Id != 0)
                {
                    <a class="btn btn-success" href="/teacher/TestQuestions/@Model.Id">
                        Питання
                    </a>
                }
            </div>
        </form>
    </div>
</div>

<script>
    $('.selectpicker').select2();
</script>

src/KAssessment/KAssessment/Views/Teacher/TestQuestions.cshtml
@model Models.Entities.Test
@{
    ViewData["Title"] = "Тест - " + Model.Name;
}
<h2>Тест - @Model.Name</h2>
<hr />
<form action="/teacher/ModifyQuestion" method="post">
    <h4>Текст питання</h4>
    <div class="row">
        <input type="hidden" name="TestId" value="@Model.Id" />
        <div class="col-md-8">
            <input type="text" class="form-control" name="QuestionText" required />
        </div>
        <div class="col-md-2">
            <button type="submit" class="btn btn-primary">Створити</button>
        </div>
    </div>
</form>
<hr />

<div id="accordion">
    @foreach (var q in Model.Questions)
    {
        <h3>@q.QuestionText</h3>
        <div>
            <div>
                <table  class="table table-sm table-striped table-bordered" id="questionAnswers@(q.Id)">
                    <tr>
                        <th>Текст</th>
                        <th>Відповідь вірна?</th>
                        <th></th>
                    </tr>
                    @Html.Partial("_QuestionAnswers",q) 
                </table>
            </div>
            <div>

                <form action="/teacher/ModifyAnswer" method="post" data-ajax-update="#questionAnswers@(q.Id)" data-ajax-complete="completed" data-ajax="true" data-ajax-method="post" id="modifyAnswerForm">
                    <div class="row">
                        <input type="hidden" name="QuestionId" id="questionId" value="@q.Id" />
                        <div class="col-md-6">
                            <input type="text" id="answerText" class="form-control" placeholder="Текст відповіді" name="Text" required />
                        </div>
                        <div class="col-md-3">
                            <div class="row">
                                <div class="col-md-6">
                                    Відповідь правильна?
                                </div>
                                <div class="col-md-4">
                                    @Html.CheckBox("IsRight",new { @class = "form-control" });
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary">Додати</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    }
</div>

<script>
    $(function () {
        $("#accordion").accordion({heightStyle: "content" });
    });

    completed = function () {
        document.getElementById("answerText").value = "";
        };
</script>

src/KAssessment/KAssessment/Views/Teacher/Tests.cshtml
@model IEnumerable<Models.Entities.TestsListItemDTO>
@{
    ViewData["Title"] = "Мої тести";
}

<h2> Мої тести</h2>
<p>
    <a class="btn btn-info" href="/teacher/modifyTest">
        Створити тест
    </a>
</p>

<div id="accordion">
    @foreach (var item in Model)
    {
        <h3>@item.Subject.Name</h3>
        <div>
            <ul>
                @foreach (var test in item.Tests)
                {
                    <li>
                        <div class="row">
                            <div class="col-md-8">
                                <a class="alert-link" style="color:blue;text-decoration:underline" href="/teacher/modifyTest?testId=@test.Id">@test.Name</a>
                            </div>
                            <div class="col-md-1">
                                <a class="btn btn-info" style="color:white" href="/teacher/testQuestions/@test.Id">Питання</a>
                            </div>
                            <div class="col-md-1">
                                
                                <form method="delete" action="/teacher/deleteTest">
                                    <input type="hidden" name="testId" value="@test.Id" />
                                    <button type="submit" class="btn btn-danger">Видалити</button>
                                </form>
                            </div>
                        </div>
                        <br />
                    </li>
                }
            </ul>
        </div>
    }
</div>

<script>
    $(function () {
        $("#accordion").accordion();
    });
</script>

src/KAssessment/KAssessment/Views/Teacher/_Answer.cshtml
@model Models.Entities.Answer
<td>@Model.Text</td>
<td>
   @(Model.IsRight?"+":"-")
</td>
<td>
    <form action="/teacher/DeleteAnswer?id=@Model.Id" data-ajax-method="delete" method="delete" data-ajax-update="#questionAnswers@(Model.QuestionId)" data-ajax="true">
        <button type="submit" class="btn btn-danger" style="color:white">Видалити</button>
    </form>
</td>

src/KAssessment/KAssessment/Views/Teacher/_QuestionAnswers.cshtml
@model  Models.Entities.Question
@foreach (var answer in Model.Answers)
{
    <tr id="ans@(answer.Id)">
        @Html.Partial("_Answer",answer)
    </tr>

}

src/KAssessment/KAssessment/Views/Teacher/_TestSessions.cshtml
@model IEnumerable<Models.Entities.TestSession>

@foreach(var item in Model)
{
    <tr>
        <td>@item.Test?.Name</td>
        <td>@(item.CreateDate.HasValue?item.CreateDate.Value.ToString():"")</td>
        <td>@(item.EndDate.HasValue?item.EndDate.Value.ToString():"")</td>
        <td>@Html.ActionLink("Результати","GroupResults","Session",new { sessionId=item.Id })</td>
    </tr>
}